ionic-team/stencil-store

README.md, src/observable-map.test.ts, src/observable-map.ts, src/subscriptions/stencil.ts, src/types.ts, test-app/src/components/simple-store/display-store.spec.ts, test-app/src/utils/greeting-store.ts
When calling `reset` in two different tests, we get the following error:
```
TypeError: Cannot read property '$hostElement$' of undefined
```
Submitting this first commit to watch it fail!
=> Reset produce some errors in tests.

.github/workflows/main.yml, package.json, test-app/package.json
=> fix(peerdep) Downgrade peer dependency and make sure the test-app is in sync with it.

README.md
=> readme: clarify that `onChange` runs on set or reset

README.md
=> fix(35): Add some documentation about subscriptions

package-lock.json, package.json
this commit increments the minor version of @stencil/core in the peer
dependencies of the package. this change is a result of the stencil team
no longer officially supporting stencil v1.x
BREAKING CHANGE: Drops support for v1.X of Stencil. Stencil projects using
v1.x of `@stencil/core` will need to [migrate to v2.x](https://github.com/ionic-team/stencil/blob/main/BREAKING_CHANGES.md#breaking-changes)
Applications using this library will need to migrate to Stencil v2.  
- Unit tests were run/passed
=> chore(dependencies): increment min. stencil version

.github/dependabot.yml
We receive Dependabot updates for packages we don't want to update ATM
this commit updates the dependabot configuration to ignore the following packages:
- `@types/node` - ignore versions of node that the project does not yet support/get built with
- `typescript` - ignore versions of typescript the Stencil ecosystem does not support
Taken directly from Stencil core's dependabot config
=> chore(github): ignore unsupported packages

.github/workflows/main.yml
we have one giant step for running ci, which makes it hard to see failures
this commit updates ci to split the various steps into distinct units of work. this allows us to better align with the stencil core repo and see failures in the pipeline more easily.
this commit moves us to only testing against the latest and greatest version of stencil. we expect the 2.X line to be backwards compatible with itself and don't see much value in testing only the latest and 2.4
this commit also updates the setup-node action to take advantage of the volta key that is in package.json
with this commit, we also update the run triggers to 'push' on main to run when a …
=> refactor(ci): split ci into distinct steps

.github/workflows/main.yml
we use version number (`/v\d/`) in our github actions definition.
this allows for auto-upgrades, but can also lead to using a potentially
malicious action.
GitHub Issue Number: 
Supersedes: https://github.com/ionic-team/stencil-store/pull/161
this commit moves the versioning scheme for `actions/checkout` to use the release specified by a specific sha (in this case v3.1.0). this is being done to provide more concrete control over which versions of various github actions that we use.
no comment is added to the file to tie the sha to the semantic version
being used. this is being done while we're trying out dependabot to manage
these dependency bumps for us (and does not know how …
=> chore(ci): switch actions/checkout to sha based versioning

.github/dependabot.yml, package-lock.json, package.json
this commit updates typescript to v4.8.4, to align with upcoming changes in the main repository where stencil core is built with v4.8 as well.
@types/node is explicitly installed to avoid an issue where it was previously reconciled as a sub-dependency of other dependencies (such as jest). this prevents a type error that was causing the build to fail when bumping typescript from v4.7 to v4.8
this commit also updates the dependabot manifest to ignore versions greater than or equal to v4.9, as it is not supported in the stencil ecosystem (at this time).
In addition to unit tests and build the continuing to pass, I also did a `diff` on the output for this …
=> chore(dev-deps): upgrade typescript to v4.8.4

.github/workflows/main.yml
We run CI against more Stencil versions than needed
this commit updates the versions of stencil that ci runs against, following the v3 release of stencil & updating the dev dependency on stencil to v3 in https://github.com/ionic-team/stencil-store/pull/210
the 'v3-next' version has been removed, as that tag resolves to stencil v3.0.0
the 'latest' verison has been removed, as it now resolves to the same version as 'DEFAULT'
Tailed CI logs
Will need to update the GitHub required checks prior to this landing
=> chore(ci): update stencil versions run post-v3

.github/workflows/main.yml
Adds Stencil v4 (beta, rc, etc.) to the CI pipeline
-
-
-
=> chore(ci): add v4 versions to ci matrix

package-lock.json, package.json
Adds Stencil V4 as peer dep
-
-
-
=> chore(deps): bump peer dep for Stencil v4

package-lock.json, package.json
We don't have `engines` specified, which is blocking #287 
this commit adds an engines field to the package to explicitly state what versions of node/npm that are currently supported. the current version of the package supports stencil v2 and up - stencil v2 supported node 12+, which is the justification for such a low version of node/npm in these fields
N/A
=> chore(package): add engines to package.json

.github/ionic-issue-bot.yml
- Replaces the Stencil Slack link with the Ionic Discord
-
-
=> chore: replace stencil slack with discord channel

.github/workflows/main.yml
this commit adds a small version comment to the `setup-node` dependency. this is being done as
https://github.com/ionic-team/stencil-store/pull/305 appears to want to bump setup-node to the latest sha, as opposed to the latest release. the intent is to merge this, rebase #305, and see what happens.
N/A
=> chore(ci): add tag to setup-node version

test-app/package-lock.json, test-app/package.json
this commit removes unneeded `@types/puppeteer`, which are now included in newer versions of puppeteer
supercedes: #309
N/A
=> chore(test-app): remove unneeded puppeteer types

.gitignore
.tgz files are tracked by git
this commit adds .tgz files to `.gitignore`, in order to prevent the results of `npm pack` from being added to the repo when using such a workflow to test a package's change
N/A
=> chore(repo): add .tgz files to gitignore

package-lock.json, package.json
use the tilde for typescript versions to match what we do in the rest of the stencil ecosystem. this also fixes a potential bug in the renovate jobs where typescript was being upgraded to 5.1.x.
=> chore(dev-deps): use tilde in typescript

renovate.json5
the `jest-cli` package _should_ be managed by renovate.
this commit re-adds the jest-cli to renovate, which we need for the test application (which itself is a stencil project). it was erroneously removed in https://github.com/ionic-team/stencil-store/pull/321.
N/A
=> chore(repo): readd jest-cli to renovate

test-app/package-lock.json, test-app/package.json
see 'new behavior' section
add `@types/node` as a dependency to the test application. previously, there was an implicit assumption this package was available. however, if it wasn't, the build for the test app would fail.
Prior to this commit, navigate to `test-app` in this repo and attempt to build the project:
```bash
npm ci && \
npm run build
```
only to be greeted with:
```
[ ERROR ]  TypeScript: node_modules/@types/node/globals.d.ts:72:13
Subsequent variable declarations must have the same type. Variable 'AbortSignal' must be of type '{ new ():
AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): …
```
=> chore(test-app): add `@types/node` to test-app

renovate.json5
Lowers the frequency that Renovate checks for dependency updates (matches Stencil Core)
=> chore(renovate): lower renovate frequency
